#!/usr/bin/env bash
# configure-urls.sh - Extract ngrok URLs and generate runtime configuration
#
# Description:
#   Fetches ngrok tunnel URLs from the ngrok API and generates:
#   1. server/.env.demo - CORS_ORIGIN for backend
#   2. public/config.js - API_BASE_URL for frontend runtime override
#
# Exit Codes:
#   0 - Success
#   1 - General error
#   2 - ngrok API not available
#   3 - jq not installed (no fallback available)
#   4 - Required URLs not found
#
# Usage:
#   ./scripts/ngrok/configure-urls.sh
#   ./scripts/ngrok/configure-urls.sh --frontend-url <url> --backend-url <url>
#
# Output:
#   FRONTEND_URL=https://xxx.ngrok-free.app
#   BACKEND_URL=https://yyy.ngrok-free.app
#   CONFIG_GENERATED=true
#
# Part of Voice-Agent-PuPuPlatter ngrok demo infrastructure

set -euo pipefail

# Script directory resolution
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Configuration
NGROK_API_PORT="${NGROK_INSPECTOR_PORT:-4041}"
NGROK_API_URL="http://localhost:${NGROK_API_PORT}/api/tunnels"
FRONTEND_PORT="${FRONTEND_PORT:-8082}"
BACKEND_PORT="${BACKEND_PORT:-3001}"

# Output paths
ENV_DEMO_FILE="${PROJECT_ROOT}/server/.env.demo"
CONFIG_JS_FILE="${PROJECT_ROOT}/public/config.js"
CONFIG_TEMPLATE_FILE="${PROJECT_ROOT}/public/config.template.js"

# Colors for output (disabled if not a terminal)
if [ -t 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m'
else
    RED=''
    GREEN=''
    YELLOW=''
    BLUE=''
    NC=''
fi

print_success() {
    printf "%b[OK]%b %s\n" "${GREEN}" "${NC}" "$1"
}

print_error() {
    printf "%b[ERROR]%b %s\n" "${RED}" "${NC}" "$1" >&2
}

print_warning() {
    printf "%b[WARN]%b %s\n" "${YELLOW}" "${NC}" "$1"
}

print_info() {
    printf "%b[INFO]%b %s\n" "${BLUE}" "${NC}" "$1"
}

# Check for jq (required for JSON parsing)
check_jq() {
    if ! command -v jq >/dev/null 2>&1; then
        print_error "jq is required but not installed"
        print_info "Install with: sudo apt install jq (Debian/Ubuntu)"
        print_info "Or: brew install jq (macOS)"
        exit 3
    fi
}

# Normalize URL: ensure https://, remove trailing slash
normalize_url() {
    local url="$1"
    # Remove trailing slash
    url="${url%/}"
    # Ensure https:// protocol
    if [[ "$url" != https://* ]]; then
        url="https://${url#http://}"
    fi
    echo "$url"
}

# Parse URLs from ngrok API response using jq
parse_ngrok_urls() {
    local response="$1"
    local frontend_url=""
    local backend_url=""

    # Extract tunnels array and find URLs by port
    # ngrok exposes tunnels with public_url and config.addr containing the port
    frontend_url=$(echo "$response" | jq -r ".tunnels[] | select(.config.addr | contains(\":${FRONTEND_PORT}\")) | .public_url" | head -1)
    backend_url=$(echo "$response" | jq -r ".tunnels[] | select(.config.addr | contains(\":${BACKEND_PORT}\")) | .public_url" | head -1)

    # Fallback: check by name if port matching fails
    if [[ -z "$frontend_url" || "$frontend_url" == "null" ]]; then
        frontend_url=$(echo "$response" | jq -r '.tunnels[] | select(.name == "frontend" or .name == "voice-frontend") | .public_url' | head -1)
    fi
    if [[ -z "$backend_url" || "$backend_url" == "null" ]]; then
        backend_url=$(echo "$response" | jq -r '.tunnels[] | select(.name == "backend" or .name == "voice-backend") | .public_url' | head -1)
    fi

    # Return normalized URLs
    if [[ -n "$frontend_url" && "$frontend_url" != "null" ]]; then
        FRONTEND_URL=$(normalize_url "$frontend_url")
    fi
    if [[ -n "$backend_url" && "$backend_url" != "null" ]]; then
        BACKEND_URL=$(normalize_url "$backend_url")
    fi
}

# Fetch URLs from ngrok API
fetch_ngrok_urls() {
    print_info "Fetching tunnel URLs from ngrok API..."

    local response
    if ! response=$(curl -s --max-time 5 "$NGROK_API_URL" 2>/dev/null); then
        print_error "Failed to connect to ngrok API at ${NGROK_API_URL}"
        print_info "Ensure ngrok is running with: ngrok start --all --config scripts/ngrok/ngrok.yml"
        exit 2
    fi

    # Check if response is valid JSON
    if ! echo "$response" | jq empty 2>/dev/null; then
        print_error "Invalid JSON response from ngrok API"
        exit 2
    fi

    # Check if tunnels exist
    local tunnel_count
    tunnel_count=$(echo "$response" | jq '.tunnels | length')
    if [[ "$tunnel_count" -eq 0 ]]; then
        print_error "No tunnels found in ngrok API response"
        exit 4
    fi

    parse_ngrok_urls "$response"
}

# Generate server/.env.demo with CORS_ORIGIN
generate_env_demo() {
    print_info "Generating server/.env.demo..."

    # Create server directory if it doesn't exist
    mkdir -p "$(dirname "$ENV_DEMO_FILE")"

    cat > "$ENV_DEMO_FILE" << EOF
# Demo mode environment overrides
# Generated by configure-urls.sh - DO NOT EDIT
# This file is ephemeral and will be deleted on shutdown

# Demo mode flag
DEMO_MODE=true

# Dynamic CORS origin from ngrok frontend tunnel
CORS_ORIGIN=${FRONTEND_URL}

# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF

    print_success "Generated ${ENV_DEMO_FILE}"
}

# Generate public/config.js from template
generate_config_js() {
    print_info "Generating public/config.js..."

    # Check template exists
    if [[ ! -f "$CONFIG_TEMPLATE_FILE" ]]; then
        print_error "Template not found: ${CONFIG_TEMPLATE_FILE}"
        exit 1
    fi

    local generated_at
    generated_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Replace placeholders in template
    sed -e "s|{{BACKEND_URL}}|${BACKEND_URL}|g" \
        -e "s|{{FRONTEND_URL}}|${FRONTEND_URL}|g" \
        -e "s|{{GENERATED_AT}}|${generated_at}|g" \
        "$CONFIG_TEMPLATE_FILE" > "$CONFIG_JS_FILE"

    print_success "Generated ${CONFIG_JS_FILE}"
}

# Output results in machine-readable format
output_results() {
    echo "FRONTEND_URL=${FRONTEND_URL}"
    echo "BACKEND_URL=${BACKEND_URL}"
    echo "CONFIG_GENERATED=true"
}

# Validate required URLs are present
validate_urls() {
    local has_error=0

    if [[ -z "${FRONTEND_URL:-}" ]]; then
        print_error "Frontend URL not found"
        has_error=1
    fi

    if [[ -z "${BACKEND_URL:-}" ]]; then
        print_error "Backend URL not found"
        has_error=1
    fi

    if [[ $has_error -eq 1 ]]; then
        print_info "Expected tunnels for ports ${FRONTEND_PORT} and ${BACKEND_PORT}"
        exit 4
    fi
}

# Parse command-line arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --frontend-url)
                FRONTEND_URL=$(normalize_url "$2")
                shift 2
                ;;
            --backend-url)
                BACKEND_URL=$(normalize_url "$2")
                shift 2
                ;;
            --help|-h)
                echo "Usage: $0 [--frontend-url <url>] [--backend-url <url>]"
                echo ""
                echo "If URLs are not provided, they will be fetched from ngrok API."
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done
}

# Main function
main() {
    FRONTEND_URL=""
    BACKEND_URL=""

    parse_args "$@"

    # Check prerequisites
    check_jq

    # If URLs not provided via args, fetch from ngrok API
    if [[ -z "$FRONTEND_URL" || -z "$BACKEND_URL" ]]; then
        fetch_ngrok_urls
    fi

    # Validate we have both URLs
    validate_urls

    # Generate configuration files
    generate_env_demo
    generate_config_js

    # Output results
    output_results

    print_success "URL configuration complete"
}

# Run main function
main "$@"
